### ISSUE TITLE
Check again test (Old template)

### ISSUE THREAD

**Issue by RonakLakhotia** [CATcher-org/pe-evaluation#3] opened 2019-03-22 07:28 UTC
# Description
I can't log in!
# Team's Response
Hi.

Because you have not signed up.
[original: nus-cs2103-AY1819S1/pe-results#1414]
 # Disputes

**Comment by testathorTutor** [comment] 2019-03-22 07:29
## Tutor's Response
ssaaa
## State the duplicated issue here, if any

**Comment by testathorTutor** [comment] 2019-04-03 09:00
## Tutor's Response
sd
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-04-03 09:03
## Tutor's Response
aa
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-04-03 11:49
## Tutor's Response
test
## State the duplicated issue here, if any
Duplicate of #5

**Comment by testathorTutor** [comment] 2019-04-03 11:51
## Tutor's Response
test






## State the duplicated issue here, if any
--

**Closed as completed** 2019-12-04 05:02 UTC
Labels: duplicate, severity.Low, team.3, response.IssueUnclear, type.FunctionalityBug, tutorial.CS2103T-W12
