### ISSUE TITLE
okay (Old template)

### ISSUE THREAD

**Issue by RonakLakhotia** [CATcher-org/pe-evaluation#4] opened 2019-03-22 07:31 UTC
# Description
<img width="1062" alt="check" src="https://user-images.githubusercontent.com/28557842/55052749-f65a3680-5094-11e9-9686-9b622c3a7628.png">

It is able to change the root password. So once someone log in through root user account, after he or she change this passwoard The other users who have not register yet cannot access ever agian.
[original: nus-cs2103-AY1819S1/pe#1378]
# Team's Response
Hi.

Ability to change root password is a feature, not a bug.

Typically, the owner of the application (perhaps manager of the wedding planning agency) holds the root account. He can decides to change his root account at any point in time (for example, if he feels that his account has been compromised). He will register the account for his employees and assign them account role (either super user, or read only user) accordingly. The employees can then change their own password later.

The other users who have not register yet cannot access ever agian. abc
[original: nus-cs2103-AY1819S1/pe-results#1414]
 ## State the duplicated issue here, if any
--
## Proposed Assignees
testathorStudent
# Items for the Tester to Verify
## 1. change of severity

Changed from `High` to `Low`

- [x] I disagree

**Reason for disagreement:** The issue is really a big problem for users

-------------------
## 2. change of type

Changed from `X` to `Y`

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

-------------------
# Tutor's Response
Looks good.
## Tutor to check
- [ ] justification for rejection
- [x] justification for duplicate
- [x] justification for downgrade

**Comment by testathorTutor** [comment] 2019-03-27 07:10
## Tutor's Response
s
## State the duplicated issue here,
        if any
--

**Comment by testathorTutor** [comment] 2019-03-27 07:10
## Tutor's Response
s
## State the duplicated issue here,
        if any
--

**Comment by testathorTutor** [comment] 2019-03-27 07:19
## Tutor's Response
Check
## State the duplicated issue here,
        if any
--

**Comment by testathorTutor** [comment] 2019-03-27 07:21
## Tutor's Response
check
## State the duplicated issue here,
        if any
--

**Comment by testathorTutor** [comment] 2019-03-27 07:35
## Tutor's Response
z
## State the duplicated issue here,
        if any
--

**Comment by testathorTutor** [comment] 2019-03-27 07:37
## Tutor's Response
a
## State the duplicated issue here,
        if any
--

**Comment by testathorTutor** [comment] 2019-03-27 07:39
## Tutor's Response
s
## State the duplicated issue here,
        if any
--

**Comment by testathorTutor** [comment] 2019-03-27 09:49
## Tutor's Response
g
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-03-27 09:49
## Tutor's Response
g
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-03-27 10:06
## Tutor's Response
z
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-03-27 10:14
## Tutor's Response
c
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-03-27 10:17
## Tutor's Response
s
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-03-27 10:20
## Tutor's Response
v
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-03-27 13:47
## Tutor's Response
x
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-03-27 14:23
## Tutor's Response
s
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-03-27 14:26
## Tutor's Response
as
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-03-29 07:12
## Tutor's Response
SADASD
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-03-29 13:58
## Tutor's Response
okay s
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-04-02 10:51
## Tutor's Response
okay
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-04-02 10:55
## Tutor's Response
okay
## State the duplicated issue here, if any
Duplicate of #3

**Comment by testathorTutor** [comment] 2019-04-02 10:56
## Tutor's Response
okay j
## State the duplicated issue here, if any
Duplicate of #3

**Comment by testathorTutor** [comment] 2019-04-02 11:06
## Tutor's Response
asd
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-04-02 11:07
## Tutor's Response
m
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-04-02 11:13
## Tutor's Response
sd
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-04-02 11:15
## Tutor's Response
okay
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-04-03 08:50
## Tutor's Response
s
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-04-03 09:05
## Tutor's Response
asdsad
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-04-03 12:35
## Tutor's Response
let us debug
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-04-03 12:44
## Tutor's Response
okay it works
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-04-05 06:58
## Tutor's Response
OKAY
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-04-05 10:04
## Tutor's Response
lets see
## State the duplicated issue here, if any
--

**Closed as completed** 2019-12-04 05:02 UTC
Labels: team.3, type.DocumentationBug, severity.High, tutorial.CS2103T-W12, response.Accepted
