### ISSUE TITLE
New issue (Old template)

### ISSUE THREAD

**Issue by RonakLakhotia** [CATcher-org/pe-evaluation#5] opened 2019-03-27 07:43 UTC
# Description
Your App crashes!!!
[original: nus-cs2103-AY1819S1/pe#1378]
# Team's Response
Hi.

You are right, this is duplicate of some issue.
[original: nus-cs2103-AY1819S1/pe-results#1414]
 ## State the duplicated issue here, if any
Duplicate of #4
## Proposed Assignees
testathorStudent
# Tutor's Response
Yes I agree
## Tutor to check
- [x] justification for duplicate

**Comment by testathorTutor** [comment] 2019-03-27 07:44
## Tutor's Response
n
## State the duplicated issue here,
        if any
--

**Comment by testathorTutor** [comment] 2019-03-27 07:47
## Tutor's Response
n
## State the duplicated issue here,
        if any
--

**Comment by testathorTutor** [comment] 2019-03-27 07:50
## Tutor's Response
j
## State the duplicated issue here, 
        if any
--

**Comment by testathorTutor** [comment] 2019-03-27 07:55
## Tutor's Response
n
## State the duplicated issue here, if any
--

**Comment by testathorTutor** [comment] 2019-03-27 08:00
## Tutor's Response
sad
## State the duplicated issue here, if any

**Comment by testathorTutor** [comment] 2019-03-27 08:00
## Tutor's Response
sad
## State the duplicated issue here, if any
3

**Comment by testathorTutor** [comment] 2019-03-27 08:06
## Tutor's Response
sad
## State the duplicated issue here, if any

**Comment by testathorTutor** [comment] 2019-03-27 08:10
## Tutor's Response
dsada
## State the duplicated issue here, if any

**Comment by testathorTutor** [comment] 2019-04-02 15:12
## Tutor's Response
sda
## State the duplicated issue here, if any
Duplicate of #3

**Comment by testathorTutor** [comment] 2019-04-03 11:54
## Tutor's Response
asd
## State the duplicated issue here, if any
Duplicate of #3

**Comment by testathorTutor** [comment] 2019-04-03 11:54
## Tutor's Response
test
## State the duplicated issue here, if any
Duplicate of #4

**Comment by testathorTutor** [comment] 2019-04-03 11:59
## Tutor's Response
test
## State the duplicated issue here, if any
Duplicate of #3

**Comment by testathorTutor** [comment] 2019-04-03 12:00
## Tutor's Response
test
## State the duplicated issue here, if any
Duplicate of #4

**Comment by testathorTutor** [comment] 2019-04-05 15:25
## Tutor's Response
t
## State the duplicated issue here, if any
Duplicate of #3

**Comment by testathorTutor** [comment] 2019-05-21 06:37
## Tutor's Response
sfsfsdvsvdf
## State the duplicated issue here, if any
--

**Closed as completed** 2019-12-04 05:02 UTC
Labels: duplicate, team.3, type.DocumentationBug, severity.Medium, tutorial.CS2103T-W12
